name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/brownuniversity/kitchen-terraform/kitchen-terraform:latest

    steps:
    - uses: actions/checkout@v1
    - name: Create Credential File
      run: |
        echo "$GCP_CREDENTIAL_JSON" > /tmp/credentials.json
      env:
        GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CREDENTIAL_JSON}}
    - name: Run Kitchen
      run: kitchen test
      env:
        TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
        TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
        TF_VAR_folder_id: ${{ secrets.GCP_FOLDER_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
